// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package cindex

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CodeElement struct {
	ID          pgtype.Int4
	FileID      int32
	ElementType string
	ElementName string
	StartLine   int32
	EndLine     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CodeFile struct {
	ID                  pgtype.Int4
	RepoID              int32
	FilePath            string
	FileName            string
	ProgrammingLanguage string
	Contents            string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type CodeRepository struct {
	ID       pgtype.Int4
	Repo     string
	RepoType string
}
