services:
  db:
    image: "postgres:16.4-alpine3.20"
    volumes:
      - ./sql:/sql
      - ./sql/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
